### ISSUE TITLE
Unhandled exception on invalid syntax

### ISSUE THREAD

**Issue by mmomtchev** [landakram/remark-wiki-link#9]
The following code produces an unhandled exception:
```js
const unified = require('unified')
const markdown = require('remark-parse')
const { wikiLinkPlugin } = require('remark-wiki-link');

let processor = unified()
    .use(markdown)
    .use(wikiLinkPlugin);

console.log(processor.parse('**Hello world!!!** [['));
```

So I am wondering if this is working as intended?
My usage case is rendering a preview while typing and this is a problem, but I wonder if it is up to the higher levels to handle it or should the plugin handle it? I haven't noticed any other `remark` plugins doing this, so I am starting at the plugin?

**Comment by mmomtchev** [comment]
```
/home/mmom/src/top-secret-project/front/node_modules/mdast-util-from-markdown/dist/index.js:412
      throw new Error(
      ^

Error: Cannot close `paragraph` (1:1-1:22): a different token (`wikiLink`, 1:20-1:1) is open
    at Object.exit (/home/mmom/src/top-secret-project/front/node_modules/mdast-util-from-markdown/dist/index.js:412:13)
    at Object.close (/home/mmom/src/top-secret-project/front/node_modules/mdast-util-from-markdown/dist/index.js:395:12)
    at compile (/home/mmom/src/top-secret-project/front/node_modules/mdast-util-from-markdown/dist/index.js:189:40)
    at fromMarkdown (/home/mmom/src/top-secret-project/front/node_modules/mdast-util-from-markdown/dist/index.js:24:27)
    at parse (/home/mmom/src/top-secret-project/front/node_modules/remark-parse/index.js:13:12)
    at Function.parse (/home/mmom/src/top-secret-project/front/node_modules/unified/index.js:284:12)
    at Object.<anonymous> (/home/mmom/src/top-secret-project/front/test-wiki-link.js:9:23)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
```

**Comment by landakram** [comment]
Thanks again for bringing this to my attention and raising the helpful PR. It should be fixed as of https://github.com/landakram/remark-wiki-link/pull/10 and v1.0.1 of the package, which is now published to npm.

Let me know if you run into any further issues!

**Comment by mmomtchev** [comment]
@landakram 
`[[t:\n` does not work with `mdast-util-from-markdown@0.8.4`
it works fine with `mdast-util-from-markdown@0.8.0`

**Comment by landakram** [comment]
Thanks, I'm able to reproduce. Working on a fix today.
